language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer install --no-interaction --prefer-source

script: phpunit --coverage-text --colors

notifications:
  email:
    - jokubas.rama+build@gmail.com