language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.5
      env: SYMFONY_VERSION='2.8.*@dev symfony/security-acl:2.8.*@dev'
    - php: 5.5
      env: SYMFONY_VERSION='3.0.*@dev symfony/security-acl:3.0.*@dev'

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true


before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit --coverage-text --colors

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email:
    - jokubas.rama+build@gmail.com